ervices:
  - type: web
    name: cloud-web
    region: frankfurt
    plan: free
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: esgi-cloud-exam-41105
          property: connectionString

databases:
  - name: esgi-cloud-exam-41105
    region: frankfurt
    plan: free
    databaseName: cloud
    user: cloud